# Generated by Django 6.0.1 on 2026-01-29 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('apy_above', 'APY goes above'), ('apy_below', 'APY goes below'), ('tvl_above', 'TVL goes above'), ('tvl_below', 'TVL goes below')], max_length=20)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=20)),
                ('chain', models.CharField(blank=True, max_length=50)),
                ('protocol', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_id', models.CharField(max_length=255)),
                ('pool_symbol', models.CharField(max_length=100)),
                ('pool_protocol', models.CharField(max_length=100)),
                ('triggered_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('message', models.TextField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='alerts.alertrule')),
            ],
            options={
                'verbose_name_plural': 'Alert histories',
            },
        ),
    ]
