# Generated by Django 6.0.1 on 2026-01-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_id', models.CharField(max_length=255, unique=True)),
                ('protocol', models.CharField(max_length=100)),
                ('chain', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=100)),
                ('apy', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tvl', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
